"""initial schema

Revision ID: 66de4c77509b
Revises: 
Create Date: 2025-11-09 19:45:37.538486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66de4c77509b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_state',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_verifier', sa.String(length=255), nullable=False),
    sa.Column('draft_club_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unique_divisions',
    sa.Column('division_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('division_id')
    )
    op.create_table('unique_locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clubs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=True)
    op.create_index(op.f('ix_clubs_user_id'), 'clubs', ['user_id'], unique=False)
    op.create_table('unique_teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['unique_divisions.division_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('home_kit', sa.String(length=255), nullable=True),
    sa.Column('away_kit', sa.String(length=255), nullable=True),
    sa.Column('teamsnap_team_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('teamsnap_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('teamsnap_user_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('access_token_enc', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token_enc', sa.String(length=2048), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'teamsnap_user_id', name='uq_club_teamsnapid')
    )
    op.create_index('ix_teamsnap_user', 'teamsnap_accounts', ['teamsnap_user_id'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('teamsnap_location_id', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('opponents',
    sa.Column('opponent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contacts_name', sa.String(length=255), nullable=True),
    sa.Column('contacts_phone', sa.String(length=50), nullable=True),
    sa.Column('contacts_email', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('teamsnap_opponent_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('opponent_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('duration_in_minutes', sa.Integer(), nullable=False),
    sa.Column('is_game', sa.Boolean(), nullable=True),
    sa.Column('is_tbd', sa.Boolean(), nullable=True),
    sa.Column('tracks_availability', sa.Boolean(), nullable=True),
    sa.Column('browser_time_zone', sa.String(length=100), nullable=True),
    sa.Column('time_zone', sa.String(length=100), nullable=True),
    sa.Column('notify_team', sa.Boolean(), nullable=True),
    sa.Column('notify_opponent', sa.Boolean(), nullable=True),
    sa.Column('notify_opponent_contacts_name', sa.String(length=255), nullable=True),
    sa.Column('notify_opponent_contacts_email', sa.String(length=255), nullable=True),
    sa.Column('notify_team_as_member_id', sa.Integer(), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.Column('updated', sa.Boolean(), nullable=False),
    sa.Column('teamsnap_event_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.opponent_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('opponents')
    op.drop_table('locations')
    op.drop_index('ix_teamsnap_user', table_name='teamsnap_accounts')
    op.drop_table('teamsnap_accounts')
    op.drop_table('teams')
    op.drop_table('unique_teams')
    op.drop_index(op.f('ix_clubs_user_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('unique_locations')
    op.drop_table('unique_divisions')
    op.drop_table('oauth_state')
    # ### end Alembic commands ###
