"""updated schema for billing

Revision ID: de75924ec473
Revises: 66de4c77509b
Create Date: 2025-11-13 09:07:23.775384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de75924ec473"
down_revision: Union[str, Sequence[str], None] = "66de4c77509b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("current_teams", sa.Integer(), nullable=False),
        sa.Column("future_teams", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "canceled",
                "past_due",
                "incomplete",
                "trialing",
                "unpaid",
                name="subscriptionstatus",
            ),
            nullable=False,
        ),
        sa.Column("current_period_end", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("subscription_id"),
        sa.UniqueConstraint("stripe_subscription_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False
    )
    op.add_column("clubs", sa.Column("club_id", sa.String(length=36), nullable=False))
    op.add_column(
        "clubs", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(None, "clubs", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        None, "clubs", "users", ["user_id"], ["user_id"], ondelete="CASCADE"
    )
    op.drop_column("clubs", "id")
    op.add_column(
        "teams", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(None, "teams", type_="foreignkey")  # type: ignore
    op.create_foreign_key(None, "teams", "clubs", ["club_id"], ["club_id"])
    op.drop_constraint(None, "teamsnap_accounts", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        None, "teamsnap_accounts", "clubs", ["club_id"], ["club_id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("user_id", sa.Integer(), nullable=False))
    op.add_column(
        "users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("users", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("id", sa.INTEGER(), nullable=False))
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "user_id")
    op.drop_constraint(None, "teamsnap_accounts", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        None, "teamsnap_accounts", "clubs", ["club_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "teams", type_="foreignkey")  # type: ignore
    op.create_foreign_key(None, "teams", "clubs", ["club_id"], ["id"])
    op.drop_column("teams", "deleted_at")
    op.add_column("clubs", sa.Column("id", sa.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, "clubs", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        None, "clubs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("clubs", "deleted_at")
    op.drop_column("clubs", "club_id")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
