"""intial schema

Revision ID: e0ec2b1ff351
Revises: 
Create Date: 2025-12-03 21:54:01.424778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ec2b1ff351'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_providers',
    sa.Column('provider_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.Enum('OAUTH2', 'API_KEY', 'OTHER', name='authtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index(op.f('ix_integration_providers_code'), 'integration_providers', ['code'], unique=True)
    op.create_table('leagues',
    sa.Column('league_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('age_group', sa.String(length=64), nullable=True),
    sa.Column('division', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clubs',
    sa.Column('club_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('club_id')
    )
    op.create_index(op.f('ix_clubs_league_id'), 'clubs', ['league_id'], unique=False)
    op.create_table('integration_accounts',
    sa.Column('integration_account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('access_token_enc', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token_enc', sa.String(length=2048), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_providers.provider_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('integration_account_id'),
    sa.UniqueConstraint('user_id', 'provider_id', 'external_user_id', name='uq_integration_account_user_provider_external')
    )
    op.create_index('ix_integration_accounts_provider_external', 'integration_accounts', ['provider_id', 'external_user_id'], unique=False)
    op.create_index(op.f('ix_integration_accounts_provider_id'), 'integration_accounts', ['provider_id'], unique=False)
    op.create_index(op.f('ix_integration_accounts_user_id'), 'integration_accounts', ['user_id'], unique=False)
    op.create_table('league_seasons',
    sa.Column('league_season_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('season_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('season_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_deadline_for_current', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_season_id')
    )
    op.create_index('ix_league_seasons_league_id', 'league_seasons', ['league_id'], unique=False)
    op.create_index('ix_league_seasons_start_end', 'league_seasons', ['season_start', 'season_end'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_verifier', sa.String(length=256), nullable=True),
    sa.Column('draft_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_providers.provider_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_provider_id'), 'oauth_states', ['provider_id'], unique=False)
    op.create_index(op.f('ix_oauth_states_user_id'), 'oauth_states', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_is_revoked'), 'sessions', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index('ix_sessions_user_id_is_revoked', 'sessions', ['user_id', 'is_revoked'], unique=False)
    op.create_table('club_integrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('integration_account_id', sa.Integer(), nullable=False),
    sa.Column('external_club_id', sa.String(length=255), nullable=False),
    sa.Column('external_name', sa.String(length=255), nullable=True),
    sa.Column('external_raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_account_id'], ['integration_accounts.integration_account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_account_id', 'external_club_id', name='uq_club_integration_external')
    )
    op.create_index(op.f('ix_club_integrations_club_id'), 'club_integrations', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_integrations_integration_account_id'), 'club_integrations', ['integration_account_id'], unique=False)
    op.create_table('league_season_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_season_id', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=False),
    sa.Column('pricing_model', sa.Enum('PER_TEAM', 'FLAT', name='pricingmodel'), nullable=False),
    sa.Column('product_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.league_season_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_season_products_league_season_id'), 'league_season_products', ['league_season_id'], unique=False)
    op.create_index(op.f('ix_league_season_products_stripe_price_id'), 'league_season_products', ['stripe_price_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_season_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('INCOMPLETE', 'INCOMPLETE_EXPIRED', 'TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', name='subscriptionstatus'), nullable=False),
    sa.Column('team_limit', sa.Integer(), nullable=False),
    sa.Column('billed_team_count', sa.Integer(), nullable=True),
    sa.Column('billing_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.league_season_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('user_id', 'league_season_id', name='uq_user_league_season_subscription')
    )
    op.create_index(op.f('ix_subscriptions_league_season_id'), 'subscriptions', ['league_season_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_club_id'), 'teams', ['club_id'], unique=False)
    op.create_table('subscription_team_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('old_team_limit', sa.Integer(), nullable=False),
    sa.Column('new_team_limit', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_team_changes_subscription_id'), 'subscription_team_changes', ['subscription_id'], unique=False)
    op.create_table('team_integrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('club_integration_id', sa.Integer(), nullable=False),
    sa.Column('external_team_id', sa.String(length=255), nullable=False),
    sa.Column('external_name', sa.String(length=255), nullable=True),
    sa.Column('external_raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_integration_id'], ['club_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_integration_id', 'external_team_id', name='uq_team_integration_external')
    )
    op.create_index(op.f('ix_team_integrations_club_integration_id'), 'team_integrations', ['club_integration_id'], unique=False)
    op.create_index(op.f('ix_team_integrations_team_id'), 'team_integrations', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_integrations_team_id'), table_name='team_integrations')
    op.drop_index(op.f('ix_team_integrations_club_integration_id'), table_name='team_integrations')
    op.drop_table('team_integrations')
    op.drop_index(op.f('ix_subscription_team_changes_subscription_id'), table_name='subscription_team_changes')
    op.drop_table('subscription_team_changes')
    op.drop_index(op.f('ix_teams_club_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_league_season_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_league_season_products_stripe_price_id'), table_name='league_season_products')
    op.drop_index(op.f('ix_league_season_products_league_season_id'), table_name='league_season_products')
    op.drop_table('league_season_products')
    op.drop_index(op.f('ix_club_integrations_integration_account_id'), table_name='club_integrations')
    op.drop_index(op.f('ix_club_integrations_club_id'), table_name='club_integrations')
    op.drop_table('club_integrations')
    op.drop_index('ix_sessions_user_id_is_revoked', table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_revoked'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_oauth_states_user_id'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_provider_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_league_seasons_start_end', table_name='league_seasons')
    op.drop_index('ix_league_seasons_league_id', table_name='league_seasons')
    op.drop_table('league_seasons')
    op.drop_index(op.f('ix_integration_accounts_user_id'), table_name='integration_accounts')
    op.drop_index(op.f('ix_integration_accounts_provider_id'), table_name='integration_accounts')
    op.drop_index('ix_integration_accounts_provider_external', table_name='integration_accounts')
    op.drop_table('integration_accounts')
    op.drop_index(op.f('ix_clubs_league_id'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_leagues_code'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_integration_providers_code'), table_name='integration_providers')
    op.drop_table('integration_providers')
    # ### end Alembic commands ###
